# Generated by Django 3.2.8 on 2021-11-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not shared', 'Not Shared')], default='Not shared', max_length=50),
        ),
    ]
