# Generated by Django 3.2.8 on 2021-11-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('time', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(default='admin', max_length=100)),
                ('debtor', models.CharField(default='admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
