# Generated by Django 3.2.8 on 2021-11-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatHokies', '0002_remove_dininglist_debtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininglist',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
