# Generated by Django 3.2.8 on 2021-11-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatHokies', '0003_alter_dininglist_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininglist',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
