# Generated by Django 3.2.8 on 2021-11-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatHokies', '0004_dininglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininglist',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eatHokies.restaurant'),
            preserve_default=False,
        ),
    ]
